server:
    port: 666

spring:
    jackson:
        default-property-inclusion: non_null
    datasource: 
        type: com.alibaba.druid.pool.DruidDataSource
        url : jdbc:p6spy:mysql://114.55.92.111:3306/zhou?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
        username : root
        password: 123456
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        validationQuery: select 1
        max-wait: 10000
        min-idle: 5
        initial-size: 5

mybatis-plus: 
    mapper-locations: com/zhou/mapper/xml/*Mapper.xml
    typeAliasesPackage: com.zhou.entity

foo : aaa
